name: build
run-name: Build
on: [push]
jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.21.x'
      - name: Test
        run: cd src ; go test
      - name: Build
        run: CGO_ENABLED=0 go build -ldflags '-extldflags "-static"' -o ./server ./server.go

  build-docker:
    runs-on: ubuntu-latest
    needs: [build-go]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          #file: ./Dockerfile
          push: false
          tags: httpserver:${{ steps.vars.outputs.sha_short }}

  view-env:
    runs-on: ubuntu-latest
    steps:
      - name: See env
        run: env

